### ISSUE TITLE
Call-time pass-by-reference has been removed

### ISSUE THREAD

**Issue by alwinkpc** [thoroc/php_ole#3]
In `class.ole_pps_root.php`, the line

```
array_push($raList, &$aThis[0]);
```

shows an error: PHP Fatal error:  Call-time pass-by-reference has been removed in /home/vagrant/app/vendor/thoroc/php_ole/src/class.ole_pps_root.php on line 305

I think this can be removed but I'm not sure what this does

**Comment by thoroc** [comment]
reading the function `_savePpsSetPnt2` (line 298-329), I am not sure why the first argument needs to be passed as a ref, either, to be honest.

**Comment by alwinkpc** [comment]
Wow, that was a fast answer. Thank you.

I'm having issues with writeexcel in a vagrant environment. Right now looking at OLE package. Guess will have to enable the debugger for this

**Comment by thoroc** [comment]
I think this lib has been developped with Php4 in mind. I have not modified it, but I have used it in a legacy environment before, that's the "reason d'etre" of this repo. I'll have another look at this argument passed by reference issue, but my gut feeling is that it isn't needed at all.

**Comment by thoroc** [comment]
It should be resolved.
